### ISSUE TITLE
report improvement - removal of "show criterion text" icon

### ISSUE THREAD

**Issue by putzhuber** [w3c/wcag-em-report-tool#351] opened 2020-04-08 11:29 UTC
removal of "show criterion text" icon in the final report (to show a pdf export or the html report to clients the report should not contain any not working links)

**Comment by rvantonisse** [comment] 2020-06-16 11:33
I thought I had commented with a refference but ok here we go again:

Duplicate of: #290

**Closed** 2020-06-16 11:33 UTC
Labels: duplicate
